#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 26 20:15:12 SGT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=superDuperVanilla.zip
